# Generated by Django 6.0.6 on 2026-06-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام آهنگ')),
                ('artist', models.CharField(max_length=200, verbose_name='هنرمند')),
                ('audio_file', models.FileField(upload_to='music/', verbose_name='فایل صوتی')),
                ('cover_image', models.ImageField(upload_to='music/covers/', verbose_name='تصویر کاور')),
            ],
        ),
    ]
