# Generated by Django 6.0.6 on 2026-06-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musictrack',
            options={'verbose_name': 'موزیک', 'verbose_name_plural': 'موزیک ها'},
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='artist',
            field=models.CharField(blank=True, max_length=200, verbose_name='هنرمند'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='music/covers/', verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام آهنگ'),
        ),
    ]
