# Generated by Django 5.1.5 on 2026-06-05 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اصلی اسلاید')),
                ('subtitle', models.CharField(max_length=200, verbose_name='زیرعنوان / توضیح کوتاه')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر بنر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'بنر اسلایدر',
                'verbose_name_plural': 'بنرهای اسلایدر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BaristaOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='پیشنهاد باریستا', max_length=50, verbose_name='برچسب بالای عنوان')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پیشنهاد (مثلاً کاپوچینو فندقی)')),
                ('image', models.ImageField(upload_to='barista/', verbose_name='عکس پس\u200cزمینه یا نمایه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'پیشنهاد باریستا',
                'verbose_name_plural': 'پیشنهادهای باریستا',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان رویداد')),
                ('image', models.ImageField(upload_to='events/', verbose_name='عکس رویداد')),
                ('desc', models.TextField(verbose_name='توضیحات رویداد')),
                ('jalali_date', models.CharField(max_length=50, verbose_name='تاریخ (مثلاً ۱۸ خرداد)')),
                ('time_range', models.CharField(max_length=50, verbose_name='ساعت (مثلاً ۱۹:۳۰ الی ۲۲:۰۰)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'ایونت / رویداد',
                'verbose_name_plural': 'ایونت\u200cها / رویدادها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
            ],
            options={
                'verbose_name': 'نوشیدنی محبوب',
                'verbose_name_plural': 'نوشیدنی\u200cهای محبوب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.RemoveField(
            model_name='favoriteproducts',
            name='Product',
        ),
        migrations.DeleteModel(
            name='TopProduct',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Settings.product', verbose_name='محصول'),
        ),
        migrations.DeleteModel(
            name='FavoriteProducts',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='لینک انگلیسی(مثلا hot)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Settings.category', verbose_name='دسته\u200cبندی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products/', verbose_name='عکس محصول'),
            preserve_default=False,
        ),
    ]
