# Generated by Django 6.0.6 on 2026-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_banner_baristaoffer_event_favoriteproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=10, verbose_name='کد میز')),
                ('table_label', models.CharField(max_length=100, verbose_name='نام/موقعیت میز')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='دیده شد / بررسی شد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
            ],
            options={
                'verbose_name': 'درخواست گارسون',
                'verbose_name_plural': 'درخواست\u200cهای گارسون',
                'ordering': ['-created_at'],
            },
        ),
    ]
